name: H.E.R.E. (Build Docker Image)

on:
  push:
    branches: [ "main" ]
    paths: [ ".github/workflows/docker-image.yml", "Dockerfile", "these-classifier.py" ]

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Docker Checkout
      uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Extract Docker Metadata
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: meyersbs/these-poc
    - uses: docker/setup-buildx-action@v1
    - name: Build and Push
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
